FROM python:3.9
COPY . /app
WORKDIR /app
RUN pip install -r requirements.txt
RUN apt-get update && apt-get -y install cron
COPY crontab /etc/cron.d/crontab
RUN crontab /etc/cron.d/crontab
CMD cron && tail -f /var/log/cron.log
