version: "3.9"
services:
  postgres:
    image: postgres:latest
    ports:
      - :5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: quotes
    volumes:
      - db-data:/var/lib/postgresql/data
    
  python:
    build:
      context: .
      dockerfile: Dockerfile.python
    user: root
    volumes:
      - .:/app
      - ./var/log:/var/log
    environment:
      - POSTGRES_HOST=quotes
    depends_on:
      - postgres

  cron:
    build:
      context: .
      dockerfile: Dockerfile.cron
    user: root
    volumes:
      - .:/app
      - ./var/log:/var/log
    depends_on:
      - postgres

volumes:
  db-data: