version: "3.8"
services:
  postgres:
    image: postgres:latest
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: quotes
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5
    restart: always
    
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    restart: on-failure
    